image_index = 2;
image_speed = 0.25;
vspeed = -5;
gravity_direction = 270;
gravity = 0.5;
if global.turn = 0
    obj_pep_battle.phase = 4;
if global.turn = 1
    obj_gustavob.phase = 4;
_image_alpha = 1;
_image_xscale = 1;
_image_yscale = 1;
depth = -16000