image_index = 2;
image_speed = 0.25;
vspeed = -10;
gravity_direction = 270;
gravity = 1;
totaldamage = 0;
reappear = 0;
pos = 0;
_image_alpha = 0.9;
_image_xscale = 1;
_image_yscale = 1;
//audio_play_sound(snd_item_use,0,0);